# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66\x65\x64\x65ration.proto\x12\x06\x63horus\"\x7f\n\x12\x46\x65\x64\x65rationEnvelope\x12\x17\n\x0fsender_instance\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x14\n\x0cmessage_type\x18\x03 \x01(\t\x12\x14\n\x0cmessage_data\x18\x04 \x01(\x0c\x12\x11\n\tsignature\x18\x05 \x01(\x0c\"{\n\x10PostAnnouncement\x12\x0f\n\x07post_id\x18\x01 \x01(\x0c\x12\x15\n\rauthor_pubkey\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontent_hash\x18\x03 \x01(\x0c\x12\x13\n\x0border_index\x18\x04 \x01(\r\x12\x14\n\x0c\x63reation_day\x18\x05 \x01(\x05\"Y\n\x10UserRegistration\x12\x13\n\x0buser_pubkey\x18\x01 \x01(\x0c\x12\x18\n\x10registration_day\x18\x02 \x01(\x05\x12\x16\n\x0e\x64\x61y_proof_hash\x18\x03 \x01(\x0c\"Z\n\x08\x44\x61yProof\x12\x12\n\nday_number\x18\x01 \x01(\x05\x12\x1c\n\x14\x63\x61nonical_proof_hash\x18\x02 \x01(\x0c\x12\x1c\n\x14validator_quorum_sig\x18\x03 \x01(\x0c\"`\n\x0fModerationEvent\x12\x12\n\ntarget_ref\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x13\n\x0breason_hash\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63reation_day\x18\x04 \x01(\x05\"l\n\x13InstanceJoinRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x17\n\x0finstance_pubkey\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontact_info\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEDERATIONENVELOPE']._serialized_start=28
  _globals['_FEDERATIONENVELOPE']._serialized_end=155
  _globals['_POSTANNOUNCEMENT']._serialized_start=157
  _globals['_POSTANNOUNCEMENT']._serialized_end=280
  _globals['_USERREGISTRATION']._serialized_start=282
  _globals['_USERREGISTRATION']._serialized_end=371
  _globals['_DAYPROOF']._serialized_start=373
  _globals['_DAYPROOF']._serialized_end=463
  _globals['_MODERATIONEVENT']._serialized_start=465
  _globals['_MODERATIONEVENT']._serialized_end=561
  _globals['_INSTANCEJOINREQUEST']._serialized_start=563
  _globals['_INSTANCEJOINREQUEST']._serialized_end=671
# @@protoc_insertion_point(module_scope)
