"""remove timestamps

Revision ID: 1dea22efcffb
Revises: 0473dd218910
Create Date: 2025-10-22 11:43:43.794324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dea22efcffb'
down_revision: Union[str, Sequence[str], None] = '0473dd218910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'created_at')
    op.drop_column('community', 'updated_at')
    op.drop_column('direct_message', 'created_at')
    op.drop_column('moderation_case', 'closed_at')
    op.drop_column('moderation_case', 'created_at')
    op.drop_column('moderation_trigger', 'created_at')
    op.drop_column('moderation_vote', 'created_at')
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'updated_at')
    op.drop_column('post_vote', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_vote', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('moderation_vote', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('moderation_trigger', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('moderation_case', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('moderation_case', sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('direct_message', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('community', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('community', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
