"""Alembic revision 268edf5d8afe."""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '268edf5d8afe'
down_revision: str | Sequence[str] | None = 'cb8f10382037'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
