"""Alembic revision 4b819fc59ba9."""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '4b819fc59ba9'
down_revision: str | Sequence[str] | None = '268edf5d8afe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
