"""Add federation_outbound table

Revision ID: 864e3cf18953
Revises: ba08dc125622
Create Date: 2025-10-23 23:20:46.004081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864e3cf18953'
down_revision: Union[str, Sequence[str], None] = 'ba08dc125622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_outbound',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('federation_outbound')
    # ### end Alembic commands ###
