"""init schemas

Revision ID: cb8f10382037
Revises: 
Create Date: 2025-10-16 20:09:15.037277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8f10382037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('internal_slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('is_profile_like', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_slug'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('community_member',
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    op.create_table('nonce_replay',
    sa.Column('pubkey_hex', sa.Text(), nullable=False),
    sa.Column('nonce_hash_hex', sa.Text(), nullable=False),
    sa.Column('day_seq', sa.BigInteger(), nullable=False),
    sa.Column('hour_seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('pubkey_hex', 'nonce_hash_hex')
    )
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ed25519_pubkey', sa.LargeBinary(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('preferred_name', sa.Text(), nullable=True),
    sa.Column('pronouns', sa.Text(), nullable=True),
    sa.Column('gender_identity', sa.Text(), nullable=True),
    sa.Column('sexual_orientation', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('pgp_public_key_asc', sa.Text(), nullable=True),
    sa.Column('mod_tokens_remaining', sa.Integer(), nullable=False),
    sa.Column('mod_tokens_day_seq', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ed25519_pubkey')
    )
    op.create_table('direct_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_index', sa.Numeric(precision=38, scale=0), nullable=False),
    sa.Column('sender_user_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('header_blob', sa.LargeBinary(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('post',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_index', sa.Numeric(precision=38, scale=0), nullable=False),
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_post_id', sa.BigInteger(), nullable=True),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(), nullable=False),
    sa.Column('moderation_state', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('moderation_case',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('opened_order_index', sa.Numeric(precision=38, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('moderation_trigger',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_user_id', sa.BigInteger(), nullable=False),
    sa.Column('day_seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'trigger_user_id')
    )
    op.create_table('post_vote',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('voter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_post_vote_direction'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'voter_user_id')
    )
    op.create_index('ix_post_vote_post_id', 'post_vote', ['post_id'], unique=False)
    op.create_table('moderation_vote',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('voter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('choice', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['moderation_case.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'voter_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation_vote')
    op.drop_index('ix_post_vote_post_id', table_name='post_vote')
    op.drop_table('post_vote')
    op.drop_table('moderation_trigger')
    op.drop_table('moderation_case')
    op.drop_table('post')
    op.drop_table('direct_message')
    op.drop_table('user_account')
    op.drop_table('nonce_replay')
    op.drop_table('community_member')
    op.drop_table('community')
    # ### end Alembic commands ###
