name: CI Checks

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Keep everything self-contained and fast
      PYTHONPATH: src
      DATABASE_URL: "sqlite+aiosqlite://"
      APP_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: py
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv and caches
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-py${{ steps.py.outputs.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies (incl. dev)
        run: poetry install --no-interaction --no-root --with dev

      - name: Lint (ruff)
        run: poetry run ruff check src tests

      - name: Run tests
        env:
          PYTEST_ADDOPTS: "--asyncio-mode=auto"
        run: poetry run pytest -q